CONFIG: Initialize Console App
Mums-Who-Code/AddressApp pull request #1
Opened 2021-11-30 17:37 UTC by GracelinJenifa

2021-11-30 18:29 UTC, ShriHumrudha requested changes
A couple of things:
1. PR title should be 'INFRA:'
2. The commit should be 'INFRA:'
3. The project name should be 'Address.ConsoleApp'

2021-12-01 14:02 UTC, GracelinJenifa commented
> A couple of things:
> 
> 1. PR title should be 'INFRA:'
> 2. The commit should be 'INFRA:'
> 3. The project name should be 'Address.ConsoleApp'

@ShriHumrudha  I have made the my changes to the PR. Kindly check.

2021-12-01 16:32 UTC, ShriHumrudha requested changes

2021-12-01 16:32 UTC, ShriHumrudha commented on Address ConsoleApp/Address. ConsoleApp.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Till it is the same
<img width="275" alt="image" src="https://user-images.githubusercontent.com/89320816/144274052-755e4ecf-a763-40c1-b372-d6765fe8211e.png">

2021-12-02 15:53 UTC, GracelinJenifa commented
@ShriHumrudha  I have Pushed a new PR #3  for this task, so closing this.

2021-12-02 15:53 UTC, closed without merging