BROKER : Insert Address
Mums-Who-Code/AddressApp pull request #6
Opened 2022-01-04 11:18 UTC by GracelinJenifa

2022-01-05 03:11 UTC, ShriHumrudha requested changes

2022-01-05 03:11 UTC, ShriHumrudha commented on AddressApp.ConsoleApp/Brokers/Storages/StorageBroker.Address.cs
> +        public Address InsertAddress(Address Address)
Correct the formatting here.

2022-01-05 03:11 UTC, ShriHumrudha commented on AddressApp.ConsoleApp/Models/Address/Address.cs
> +
Remove the extra line.

2022-01-06 10:56 UTC, GracelinJenifa commented on AddressApp.ConsoleApp/Brokers/Storages/StorageBroker.Address.cs
> +        public Address InsertAddress(Address Address)
Please check I have corrected it.

2022-01-06 10:57 UTC, GracelinJenifa commented on AddressApp.ConsoleApp/Models/Address/Address.cs
> +
Extra line removed.

2022-01-08 00:47 UTC, ShriHumrudha approved these changes

2022-01-09 17:07 UTC, merged